[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ['-Clink-arg=-Tsrc/ld/script.ld']

[target.riscv64gc-unknown-none-elf]
runner = """qemu-system-riscv64
-cpu rv64,h=off
-M virt
-m 150M
-s
-nographic
-kernel """

#runner = """ qemu-system-riscv64
#-cpu rv64
#-M virt
#-m 128M
#-smp 4
#-drive if=none,format=raw,file=hdd.dsk,id=foo
#-device virtio-blk-device,scsi=off,drive=foo
#-device virtio-rng-device
#-device virtio-gpu-device
#-device virtio-net-device
#-device virtio-tablet-device
#-device virtio-keyboard-device
#-serial mon:stdio
#-nographic
#-bios none
#-kernel """
